# Generated by Django 5.0 on 2024-03-25 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("title", models.CharField(default="Name", max_length=255)),
                ("address", models.CharField(default="Ardabil", max_length=255)),
                ("floor", models.IntegerField(default=1)),
                ("area", models.FloatField(default=0)),
                ("licence", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Spent",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("category", models.CharField(max_length=255)),
                ("subject", models.CharField(max_length=255)),
                ("building", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("price", models.IntegerField()),
            ],
            options={
                "ordering": ["price"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
