# Generated by Django 5.0 on 2024-03-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calculation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spent",
            name="date",
            field=models.CharField(max_length=5),
        ),
    ]
