# Generated by Django 5.0.3 on 2024-03-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calculation", "0002_alter_spent_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="licence",
            field=models.CharField(max_length=10),
        ),
    ]
