# Generated by Django 5.0.3 on 2024-03-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calculation", "0003_alter_building_licence"),
    ]

    operations = [
        migrations.AddField(
            model_name="spent",
            name="payer",
            field=models.CharField(default="کریم", max_length=255),
        ),
    ]
