# Generated by Django 5.0 on 2024-04-12 19:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("calculation", "0004_spent_payer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="spent",
            options={"ordering": ["id"]},
        ),
    ]
